# Generated by Django 3.2.9 on 2022-01-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220118_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details2',
            field=models.TextField(blank=True),
        ),
    ]
