# Generated by Django 3.2.9 on 2022-01-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_details2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='block_quote',
            field=models.TextField(blank=True),
        ),
    ]
