# Generated by Django 3.2.9 on 2022-02-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_block_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='details4',
            field=models.TextField(blank=True),
        ),
    ]
