# Generated by Django 3.2.9 on 2022-02-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220213_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='details6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='details7',
            field=models.TextField(blank=True),
        ),
    ]
