# Generated by Django 3.2.9 on 2022-02-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20220213_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details8',
            field=models.TextField(blank=True),
        ),
    ]
