# Generated by Django 3.2.9 on 2022-02-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_details8'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='author_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='author_img',
            field=models.ImageField(blank=True, upload_to='author_img/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='event',
            name='author_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
