# Generated by Django 3.2.9 on 2022-03-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_category_fa_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='main_image64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
