# Generated by Django 3.2.9 on 2022-03-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_main_image64'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author_img64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
