# Generated by Django 3.2.9 on 2022-06-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_author_img64'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook_iink',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
