# Generated by Django 3.2.9 on 2022-06-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20220605_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='facebook_iink',
        ),
        migrations.RemoveField(
            model_name='event',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='whatsapp_link',
        ),
    ]
