# Generated by Django 3.2.9 on 2022-03-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image1_64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image2_64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image3_64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
