# Generated by Django 3.2.9 on 2022-03-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220307_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(upload_to='projects_sub/%Y/%m/%d/'),
        ),
    ]
